name:                uno
version:             0.1.0.0
github:              "gpittarelli/uno"
license:             MIT
author:              "George Pittarelli"
maintainer:          "g@gjp.cc"
copyright:           "2017 George Pittarelli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Basic uno simulation
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/uno#readme>

dependencies:
- base >= 4.7 && < 5
- random
- random-shuffle
- split
- MonadRandom
- lens

library:
  source-dirs: src

ghc-options:
  - -fno-warn-missing-signatures

executables:
  uno-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno

tests:
  uno-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uno
